server:
  port: 8005
spring:
  application:
    name: cloud-provider-payment
  cloud:
    consul:
      port: 8500
      host: localhost
      discovery:
        service-name: ${spring.application.name}
        prefer-ip-address: true