server:
  port: 80
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000

logging:
  level:
    com.cloud.service.ProviderSerivce: debug
spring:
  application:
    name: cloud-consumer-openfeign
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1

CLOUD-PROVIDER-HYSTRIX-PAYMENT:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
