server:
  port: 5000

spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/fosulzh/config.git
          search-paths:
            - spring-cloud
          username: 1429118997@qq.com
          password: 440883lizhihai
      label: master
  rabbitmq:
    host: 120.79.195.32
    port: 5672
    username: guest
    password: guest
eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh"
