server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment_routes1
          uri: lb://CLOUD-PROVIDER-SERVICE
          predicates:
            - Path=/payment/get/**

        - id: payment_routes2
          uri: lb://CLOUD-PROVIDER-SERVICE
          predicates:
            - Path=/payment/port/**
#            - After=2020-05-06T14:08:30.900+08:00[Asia/Shanghai]
#            - Cookie=username,\d+
#            - Query=parameter,lizhihai

eureka:
  instance:
    prefer-ip-address: true
    instance-id: cloud-gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

